# Generated by Django 5.1 on 2026-01-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
