# Generated by Django 5.1 on 2026-01-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactme_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactME',
            new_name='Contact',
        ),
    ]
