# Generated by Django 5.1 on 2026-01-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('vacancy', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
            ],
        ),
    ]
