# Generated by Django 5.1 on 2026-01-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_job_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_listing',
            name='job_type',
            field=models.CharField(choices=[(' Part-time', 'Part-time'), ('on-site', 'on-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=50),
        ),
    ]
