# Generated by Django 5.1 on 2026-01-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_job_listing_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_listing',
            name='published_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
