# Generated by Django 5.1 on 2026-01-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_job_listing_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_listing',
            name='job_type',
            field=models.CharField(choices=[(' Part-time', 'Part-time'), ('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=50),
        ),
    ]
