# Generated by Django 5.1 on 2026-01-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_job_listing_job_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Popolar_Categories',
            new_name='Popolar_Categorie',
        ),
    ]
