# Generated by Django 5.1 on 2026-01-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_popolar_categories_popolar_categorie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job_Listing',
        ),
        migrations.DeleteModel(
            name='Popolar_Categorie',
        ),
    ]
