# Generated by Django 5.1 on 2026-02-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_job',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post_job',
            name='Benefits',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post_job',
            name='Qualifications',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post_job',
            name='Responsibility',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
