# Generated by Django 5.1 on 2026-02-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_post_job_slug_alter_post_job_benefits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_job',
            name='Benefits',
        ),
        migrations.RemoveField(
            model_name='post_job',
            name='Qualifications',
        ),
    ]
