# Generated by Django 5.1 on 2026-01-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('photo_company', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('Job_description', models.TextField()),
                ('Responsibility', models.TextField()),
                ('Qualifications', models.TextField()),
                ('Benefits', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[(' Part-time', 'Part-time'), ('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=50)),
                ('description', models.TextField()),
                ('published_at', models.DateField(auto_now_add=True)),
                ('Vacancy', models.IntegerField()),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
