# Generated by Django 5.1 on 2026-01-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job_Details',
            new_name='Job_Detail',
        ),
    ]
