# Generated by Django 5.1 on 2026-01-27 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_job_details_job_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_detail',
            name='description',
        ),
    ]
