# Generated by Django 5.1 on 2026-01-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_remove_job_detail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_detail',
            name='Benefits',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='Job_description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='Qualifications',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='Responsibility',
            field=models.TextField(max_length=1000),
        ),
    ]
