# Generated by Django 5.1 on 2026-02-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_detail_benefits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('website_portfolio_link', models.URLField(blank=True, null=True)),
                ('cv', models.FileField(upload_to='cv/')),
                ('cover_letter', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Job_Detail',
        ),
    ]
