# Generated by Django 5.1 on 2026-02-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_jobapply_delete_job_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobApply',
            new_name='JobApplication',
        ),
    ]
